/** All user-facing copy lives here so translating later is a single-file job. */
export const t = {
  appName: 'PDF Editor',
  tagline: 'Delete pages from a PDF, right in your browser.',
  privacy: 'Your file never leaves your device. Everything happens locally in this tab.',
  dropTitle: 'Drop a PDF here',
  dropOr: 'or',
  chooseFile: 'Choose a PDF',
  dropActive: 'Drop to open',
  openAnother: 'Open another PDF',
  download: 'Download',
  undo: 'Undo',
  redo: 'Redo',
  zoomIn: 'Zoom in',
  zoomOut: 'Zoom out',
  fitWidth: 'Fit width',
  pages: 'Pages',
  page: (n: number) => `Page ${n}`,
  pageOf: (n: number, total: number) => `Page ${n} of ${total}`,
  select: (n: number) => `Select page ${n}`,
  deletePage: (n: number) => `Delete page ${n}`,
  deleteSelected: (n: number) => `Delete ${n} selected`,
  selectAll: 'Select all',
  clearSelection: 'Clear',
  deleted: (n: number) => (n === 1 ? 'Deleted 1 page' : `Deleted ${n} pages`),
  cannotDeleteAll: 'A PDF needs at least one page, so not every page can be deleted.',
  toggleSidebar: 'Toggle page list',
  unsavedConfirm: 'You have unsaved changes. Open a different PDF and discard them?',
  passwordTitle: 'This PDF is password-protected',
  passwordBody: (name: string) => `Enter the password to open ${name}.`,
  passwordLabel: 'Password',
  passwordWrong: 'That password is incorrect. Try again.',
  passwordOpen: 'Open',
  cancel: 'Cancel',
  readOnlyBanner:
    'This PDF is password-protected. You can view it, but editing and downloading protected PDFs is not supported yet.',
  errNotPdf: 'That file does not look like a PDF.',
  errEmpty: 'That file is empty.',
  errTooLarge: (mb: number) =>
    `That file is ${mb} MB. Very large PDFs can exhaust your browser's memory; try one under 200 MB.`,
  errLoad: (detail: string) => `Could not open that PDF: ${detail}`,
  errExport: (detail: string) => `Could not build the PDF: ${detail}`,
  opening: 'Opening…',
  building: 'Preparing download…',
  footerNote: 'Open source · MIT licensed',
  githubLabel: 'Source on GitHub',
  privacyLabel: 'Privacy',
}
